import type { Match } from "@/types/match";

// Mock data representing the schedule from your Google Sheets
export const mockMatches: Match[] = [
  {
    id: "1",
    competition: "Champions_League",
    matchday: "QF",
    date: "2025-04-08",
    time: "21:00",
    homeTeam: "Real Madrid",
    awayTeam: "Manchester City",
    status: "SCHEDULED",
    score: "",
    stage: "Quarter Final",
    priority: "High",
    priorityScore: 10,
    reason: "Champions/Final, Star Team, Prime Time, Knockout Stage",
    channel: "1001 Sports",
    studio: "Yes",
  },
  {
    id: "2",
    competition: "LaLiga",
    matchday: "32",
    date: "2025-04-12",
    time: "20:00",
    homeTeam: "Barcelona",
    awayTeam: "Atletico Madrid",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "High",
    priorityScore: 5,
    reason: "Star Team, Prime Time",
    channel: "LaLiga TV",
    studio: "No",
  },
  {
    id: "3",
    competition: "Premier_League",
    matchday: "33",
    date: "2025-04-13",
    time: "17:30",
    homeTeam: "Liverpool",
    awayTeam: "Manchester United",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "High",
    priorityScore: 5,
    reason: "Star Team, Prime Time",
    channel: "TOD",
    studio: "Yes",
  },
  {
    id: "4",
    competition: "Serie_A",
    matchday: "31",
    date: "2025-04-14",
    time: "19:45",
    homeTeam: "Inter Milan",
    awayTeam: "Juventus",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "High",
    priorityScore: 5,
    reason: "Star Team, Prime Time",
    channel: "Starzplay",
    studio: "No",
  },
  {
    id: "6",
    competition: "LaLiga",
    matchday: "33",
    date: "2025-04-19",
    time: "16:00",
    homeTeam: "Valencia",
    awayTeam: "Sevilla",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "Medium",
    priorityScore: 2,
    reason: "",
    channel: "LaLiga TV",
    studio: "No",
  },
  {
    id: "7",
    competition: "Champions_League",
    matchday: "SF",
    date: "2025-04-29",
    time: "21:00",
    homeTeam: "Arsenal",
    awayTeam: "Bayern Munich",
    status: "SCHEDULED",
    score: "",
    stage: "Semi Final",
    priority: "High",
    priorityScore: 10,
    reason: "Champions/Final, Star Team, Prime Time, Knockout Stage",
    channel: "1001 Sports",
    studio: "Yes",
  },
  {
    id: "8",
    competition: "Premier_League",
    matchday: "35",
    date: "2025-04-26",
    time: "15:00",
    homeTeam: "Chelsea",
    awayTeam: "Tottenham",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "High",
    priorityScore: 3,
    reason: "Star Team",
    channel: "TOD",
    studio: "No",
  },
  {
    id: "9",
    competition: "Europa_League",
    matchday: "SF",
    date: "2025-05-01",
    time: "20:00",
    homeTeam: "AC Milan",
    awayTeam: "Roma",
    status: "SCHEDULED",
    score: "",
    stage: "Semi Final",
    priority: "Medium",
    priorityScore: 4,
    reason: "Star Team, Knockout Stage",
    channel: "1001 Sports",
    studio: "Yes",
  },
  {
    id: "10",
    competition: "Ligue_1",
    matchday: "32",
    date: "2025-04-20",
    time: "21:00",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    status: "SCHEDULED",
    score: "",
    stage: "Regular Season",
    priority: "High",
    priorityScore: 5,
    reason: "Star Team, Prime Time",
    channel: "Starzplay",
    studio: "No",
  },
];
